config/routes.rb
DemoApp::Application.routes.draw do
  resources :contact_user_assocs

  resources :contacts

  resources :users

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :phone_number
  has_many :contact_user_assoc
  validates :phone_number, :length => { :maximum => 10 }
end

app/models/contact_user_assoc.rb
class ContactUserAssoc < ActiveRecord::Base
  attr_accessible :contact_id, :user_id
  belongs_to :user
  belongs_to :contact
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password
  has_many :contact_user_assoc
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_user_assocs_controller.rb
class ContactUserAssocsController < ApplicationController
  # GET /contact_user_assocs
  # GET /contact_user_assocs.json
  def index
    @contact_user_assocs = ContactUserAssoc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contact_user_assocs }
    end
  end

  # GET /contact_user_assocs/1
  # GET /contact_user_assocs/1.json
  def show
    @contact_user_assoc = ContactUserAssoc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact_user_assoc }
    end
  end

  # GET /contact_user_assocs/new
  # GET /contact_user_assocs/new.json
  def new
    @contact_user_assoc = ContactUserAssoc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact_user_assoc }
    end
  end

  # GET /contact_user_assocs/1/edit
  def edit
    @contact_user_assoc = ContactUserAssoc.find(params[:id])
  end

  # POST /contact_user_assocs
  # POST /contact_user_assocs.json
  def create
    @contact_user_assoc = ContactUserAssoc.new(params[:contact_user_assoc])

    respond_to do |format|
      if @contact_user_assoc.save
        format.html { redirect_to @contact_user_assoc, notice: 'Contact user assoc was successfully created.' }
        format.json { render json: @contact_user_assoc, status: :created, location: @contact_user_assoc }
      else
        format.html { render action: "new" }
        format.json { render json: @contact_user_assoc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contact_user_assocs/1
  # PUT /contact_user_assocs/1.json
  def update
    @contact_user_assoc = ContactUserAssoc.find(params[:id])

    respond_to do |format|
      if @contact_user_assoc.update_attributes(params[:contact_user_assoc])
        format.html { redirect_to @contact_user_assoc, notice: 'Contact user assoc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact_user_assoc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_user_assocs/1
  # DELETE /contact_user_assocs/1.json
  def destroy
    @contact_user_assoc = ContactUserAssoc.find(params[:id])
    @contact_user_assoc.destroy

    respond_to do |format|
      format.html { redirect_to contact_user_assocs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_user_assocs_helper.rb
module ContactUserAssocsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact_user_assocs/_form.html.erb
<%= form_for(@contact_user_assoc) do |f| %>
  <% if @contact_user_assoc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_user_assoc.errors.count, "error") %> prohibited this contact_user_assoc from being saved:</h2>

      <ul>
      <% @contact_user_assoc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :contact_id %><br />
    <%= f.number_field :contact_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_user_assocs/edit.html.erb
<h1>Editing contact_user_assoc</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_user_assoc %> |
<%= link_to 'Back', contact_user_assocs_path %>

app/views/contact_user_assocs/index.html.erb
<h1>Listing contact_user_assocs</h1>

<table>
  <tr>
    <th>User</th>
    <th>Contact</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contact_user_assocs.each do |contact_user_assoc| %>
  <tr>
    <td><%= contact_user_assoc.user_id %></td>
    <td><%= contact_user_assoc.contact_id %></td>
    <td><%= link_to 'Show', contact_user_assoc %></td>
    <td><%= link_to 'Edit', edit_contact_user_assoc_path(contact_user_assoc) %></td>
    <td><%= link_to 'Destroy', contact_user_assoc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact user assoc', new_contact_user_assoc_path %>

app/views/contact_user_assocs/new.html.erb
<h1>New contact_user_assoc</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_user_assocs_path %>

app/views/contact_user_assocs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @contact_user_assoc.user_id %>
</p>

<p>
  <b>Contact:</b>
  <%= @contact_user_assoc.contact_id %>
</p>


<%= link_to 'Edit', edit_contact_user_assoc_path(@contact_user_assoc) %> |
<%= link_to 'Back', contact_user_assocs_path %>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Phone number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.first_name %></td>
    <td><%= contact.last_name %></td>
    <td><%= contact.phone_number %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @contact.last_name %>
</p>

<p>
  <b>Phone number:</b>
  <%= @contact.phone_number %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>